# Mongo-Sync Configurations

source:
  db: 'local_db_name'
  host: 'some.url.com'
  username: 'mongo_user'
  password: 'mongo_pass'
  authentication:
    db: 'admin'

dest:
  db: 'remote_db_name'
  host: 'some.url.com'
  username: 'mongo_user'
  password: 'mongo_pass'
  authentication:
    db: 'admin'
