# Mongo-Sync Configurations

source:
  uri: 'uri'
  username: 'mongo_user'
  password: 'mongo_pass'
  authentication:
    db: 'admin'

dest:
  uri: 'uri'
  username: 'mongo_user'
  password: 'mongo_pass'
  authentication:
    db: 'admin'